- name: Install PostgreSQL packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - postgresql-client
    - libpq-dev
    - python-pygresql

- name: Install pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/9.5/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
  notify:
    - restart postgresql

- name: Install Backupninja configuration
  template:
    src: 20.pgsql.j2
    dest: /etc/backup.d/20.pgsql
    owner: root
    group: root
    mode: 0600