- hosts: all
  gather_facts: False

  tasks:
  - name: Ensure Python is installed
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: all
  tasks:
    - include_vars: postfix-secrets.yml

- hosts: all
  roles:
    - role: basic
    - role: postfix
    - role: passenger
    - role: certbot
    - role: mysql
    - role: postgresql
    - role: elasticsearch
    - role: interactiveliterature.org