- debconf:
    name: mysql-server
    question: mysql-server/root_password
    value: ""
    vtype: password

- debconf:
    name: mysql-server
    question: mysql-server/root_password_again
    value: ""
    vtype: password

- name: Install MySQL packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python-mysqldb

- name: Install Backupninja configuration
  template:
    src: 20.mysql.j2
    dest: /etc/backup.d/20.mysql
    owner: root
    group: root
    mode: 0600