- name: Add Certbot PPA
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install Certbot + nginx plugin
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot
    - python-certbot-nginx

- name: Set up autorenew
  cron:
    hour: 12
    minute: "6,15"
    user: root
    job: "certbot renew --quiet --renew-hook 'service nginx reload'"